language: go
go: 1.9
sudo: true # give us 7.5GB and >2 bursted cores.
before_install:
    # Dep for Go dependency management.
    - go get -v github.com/golang/dep/cmd/dep
    # Gometalinter for good Go linting/hygiene.
    - go get -v github.com/alecthomas/gometalinter
    - gometalinter --install
    # Node.js 6.10.2 for Pulumi Fabric's Node.js runtime.
    - nvm install v6.10.2
    # Install the AWS CLI so that we can publish the resulting release (if applicable) at the end.
    - pip install --upgrade --user awscli
install:
    # Clone the Pulumi repo and use install-locked.sh to install Pulumi components based on our Gopkg.lock.
    - git clone git@github.com:pulumi/home ${GOPATH}/src/github.com/pulumi/home
    - ${GOPATH}/src/github.com/pulumi/home/scripts/install-locked.sh /opt/pulumi pulumi
    # Now restore all dependencies, after cloning, to rebuild vendor appropriately.
    - dep ensure
before_script:
    - export PATH=/opt/pulumi/bin:$PATH
script:
    - make all
    - if [ $TRAVIS_EVENT_TYPE = "push" ] && [ $TRAVIS_BRANCH = "master" ]; then PUBFORCE=true make publish; fi
notifications:
  webhooks: https://mv7ysv9978.execute-api.us-west-2.amazonaws.com/stage/travis

