[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "1ff84c1991295589b85f0ce6bf90a1b09d5a63c0"

[[override]]
  name = "github.com/pulumi/pulumi-terraform"
  revision = "e491282413eda359b0729542377f16a1a1231460"

[[override]]
  name = "github.com/hashicorp/terraform"
  source = "github.com/pulumi/terraform"
  branch = "pulumi-master"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-aws"
  source = "github.com/pulumi/terraform-provider-aws"
  branch = "pulumi-master"
