[[override]]
  name = "github.com/pulumi/pulumi"
  version = "v0.12.2"

[[override]]
  name = "github.com/pulumi/pulumi-terraform"
  revision = "ea783305995aa83b79d503187d446bbd0c55505e"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-aws"
  source = "github.com/pulumi/terraform-provider-aws"
  branch = "pulumi-master"
