[[override]]
  name = "github.com/pulumi/pulumi"
  branch = "release/0.12"

[[override]]
  name = "github.com/pulumi/pulumi-terraform"
  branch = "release/0.12"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-aws"
  source = "github.com/pulumi/terraform-provider-aws"
  branch = "pulumi-master"
