[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "9ba6584bbfbda7c54e116b0e04c93c8480a5ed28"

[[override]]
  name = "github.com/pulumi/pulumi-terraform"
  revision = "7f0caee9d5a172c0ebd47f6a2ed99a5ba2132f19"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-aws"
  source = "github.com/pulumi/terraform-provider-aws"
  branch = "pulumi-master"
