[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "ed0c068651cffbdffe648e215caf0b0c4101a841"

[[override]]
  name = "github.com/pulumi/pulumi-terraform"
  revision = "346b5844c168a88de621e2146ac590f219fce27b"

[[override]]
  name = "github.com/hashicorp/terraform"
  source = "github.com/pulumi/terraform"
  branch = "pulumi-master"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-aws"
  source = "github.com/pulumi/terraform-provider-aws"
  branch = "pulumi-master"
